# Generated by Django 4.2.7 on 2023-11-25 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video_file',
            field=models.FileField(default=datetime.datetime(2023, 11, 25, 7, 29, 40, 139487, tzinfo=datetime.timezone.utc), upload_to='videos/'),
            preserve_default=False,
        ),
    ]
